include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [vendor/**]

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    omit_local_variable_types: false
    unnecessary_library_directive: false
