name: arquivolta
description: Desktop installer / updater for the Arquivolta project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  archive: ^3.2.0
  bitsdojo_window: ^0.1.1+1
  ffi: ^1.1.2
  fluent_ui: ^3.9.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+1
  http: ^0.13.4
  path: ^1.8.0
  path_provider: ^2.0.9
  squirrel: ^0.1.0
  very_good_analysis: ^2.4.0
  win32: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.1.2
  test: ^1.10.1

msix_config:
  display_name: Arquivolta
  publisher_display_name: Arquivolta
  identity_name: dev.arquivolta.desktop
  msix_version: 0.1.0.0
  logo_path: resources/logo-msix.png
  build_windows: false
  capabilities: "runFullTrust"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
