name: arquivolta
description: Desktop installer / updater for the Arquivolta project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.3.6+1

environment:
  sdk: ">=3.0.0 <=9.0.0"

dependencies:
  archive: ^3.3.7
  async: ^2.11.0
  beamer: ^1.5.6
  dcache: ^0.4.0
  ffi: ^2.0.2
  fluent_ui: ^4.6.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_hooks: ^0.18.6
  get_it: ^7.2.0
  http: ^1.1.0
  logger: ^1.1.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  sentry_flutter: ^7.8.0
  squirrel: ^0.1.0
  very_good_analysis: ^5.0.0+1
  win32: ^5.0.5
  window_manager: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.15.0
  test: ^1.10.1

msix_config:
  display_name: Arquivolta
  publisher_display_name: Arquivolta
  identity_name: dev.arquivolta.desktop
  msix_version: 0.3.6.0
  logo_path: resources/logo-msix.png
  build_windows: false
  capabilities: "runFullTrust"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
assets:
  - assets/finished.webp
# To add assets to your application, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
