name: Test and Build MSIX Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

# NB: This shouldn't be hardcoded but I can't seem to reference RUNNER_TEMP
# from here
env:
  PUB_CACHE: "D:\\pubcache"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Create pub cache
        run: mkdir "${{env.PUB_CACHE}}"

      - name: Cache Flutter deps
        uses: actions/cache@v3
        with:
          path: ${{env.PUB_CACHE}}
          key: ${{ hashFiles('pubspec.lock')}}

      - name: Install dependencies
        run: ./flutterw pub get

      - name: Analyze project source
        run: ./flutterw analyze

      - name: Run tests
        run: ./flutterw test

      - name: Build the app (Windows)
        run: ./flutterw build windows "--dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}"

      - name: Build the app (Web)
        run: ./flutterw build web

      - name: Copy assets into place
        run: mkdir ./build/windows/runner/Release/assets ; cp ./assets/* ./build/windows/runner/Release/assets

      - name: Package the app as MSIX
        if: github.ref == 'refs/heads/main'
        run: ./flutterw pub run msix:create --install-certificate false

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: cd build/web ; mkdir '.vercel'; New-Item -Type file -Value '${{ secrets.VERCEL_PROJECT_JSON }}' -Path '.vercel/project.json' ; npx vercel --prod --token '${{ secrets.VERCEL_TOKEN }}' --yes

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/windows/runner/Release
