name: Test and Build MSIX Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

# NB: This shouldn't be hardcoded but I can't seem to reference RUNNER_TEMP
# from here
env:
  PUB_CACHE: "D:\\pubcache"
  SENTRY_DSN: $${ secrets.SENTRY_DSN }

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Create pub cache
        run: mkdir "${{env.PUB_CACHE}}"

      - name: Cache Flutter deps
        uses: actions/cache@v2
        with:
          path: ${{env.PUB_CACHE}}
          key: ${{ hashFiles('pubspec.lock')}}

      - name: Install dependencies
        run: ./flutterw pub get

      - name: Analyze project source
        run: ./flutterw analyze

      - name: Run tests
        run: ./flutterw test

      - name: Build the app
        run: ./flutterw build windows "--dart-define=SENTRY_DSN=$env:SENTRY_DSN"

      - name: Copy assets into place
        run: mkdir ./build/windows/runner/Release/assets ; cp ./assets/* ./build/windows/runner/Release/assets

      - name: Package the app as MSIX
        run: ./flutterw pub run msix:create --install-certificate false

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/windows/runner/Release
