name: Run Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: ./flutterw pub get
        
      - name: Analyze project source
        run: ./flutterw analyze

      - name: Run tests
        run: ./flutterw test
